### ISSUE TITLE
rework landing page language

### ISSUE THREAD

**Issue by javamonn** [literal-io/literal#66]
- communicate problem and solution more clearly, reduce emphasis on "what it is"
- tweak positioning statement, "mobile first", maybe include under primary CTA
- emphasize position within knowledge management space: frontline tool to augment the reading experience, not a general purpose note taking tool
- update action buttons 
  - "{android icon} Install Android App"
  - "{ios icon}" Sign Up for iOS Waitlist
 - philosophy (e.g. https://neuron.zettel.page/philosophy)
 - pitch / antipitch (e.g. https://reactnavigation.org/docs/4.x/limitations)

**Comment by javamonn** [comment]
> Might be easier to explain what it is with examples:
For writers this..
For book readers this..
For students this..

**Comment by idkjs** [comment]
@javamonn  Happy to help if you want it.

**Comment by javamonn** [comment]
@idkjs for sure! I may bounce some ideas for copy and / or designs off of you when I get around to this. If you're interested in contributing I think this would be a good entry issue for writing code once the designs are baked, but the repo is still missing onboarding documentation. :sweat_smile:

**Comment by idkjs** [comment]
Lead the way, bruh. Should do some onboarding documentation, indeed. So folk dont have to hunt for makefiles and what not. All in due time. Deep work here. Thanks for sharing it.
